### ISSUE TITLE
Add attendee property

### ISSUE THREAD

**Issue by markuspoerschke** [markuspoerschke/iCal#190]
https://tools.ietf.org/html/rfc5545#section-3.8.4.1

**Comment by ggiorginogrifo** [comment]
Dear @markuspoerschke, i'm working on this issue on a [public fork](https://github.com/giuseppenucifora/ical/tree/feature/add-attendee).
If you want, you can create a branch and i will push my changes (it's WIP, not done) on that branch, so when i'm done i will send you a message and you / your coworkers can do a code review.

What do you think?
Best regards,

Gregorio

**Comment by giorginogreg** [comment]
Dear @markuspoerschke, i'm working on this issue on a [public fork](https://github.com/giuseppenucifora/ical/tree/feature/add-attendee).
If you want, you can create a branch and i will push my changes (it's WIP, not done) on that branch, so when i'm done i will send you a message and you / your coworkers can do a code review.

What do you think?
Best regards,

Gregorio

**Comment by markuspoerschke** [comment]
@giorginogreg The best way will be a PR to this project. Just contact me, once you have something to show!

Thanks in advance!

**Comment by giorginogreg** [comment]
@markuspoerschke, I'm stuck with the calendar user type implementation.
Diving in the deep, I am trying to replicate the TimeZoneTransitionType class, because my new class (CalendarUserType) is similar to that, but I fail the tests 'cause when them try to compare the type of CalendarUserType, it return always the first type, even if they're not the same.
Attached some images that try to explain my problem.

![Schermata 2021-10-08 alle 09 10 50](https://user-images.githubusercontent.com/29749458/136513597-62c76260-c08b-4972-a439-fe2fcb16af76.png)

Class EventFactory:

![Schermata 2021-10-08 alle 09 11 44](https://user-images.githubusercontent.com/29749458/136513696-5e91fbe0-1290-44bb-b827-7630908821f9.png)

EventFactoryTest :
![Schermata 2021-10-08 alle 09 12 17](https://user-images.githubusercontent.com/29749458/136513748-953f3c2e-f668-4568-a364-7918149230c9.png)

I've tried also to debug attendee creation, and it seems that the class CalendarUserType has the properties filled with each test, they doesn't reset.

Can you give me some help? Can we try a collaborative session of coding? Thank you so much, and sorry for my bad English!
😄

**Comment by giorginogreg** [comment]
> @giorginogreg The best way will be a PR to this project. Just contact me, once you have something to show!
> 
> Thanks in advance!

@markuspoerschke i've finally finished this feature, please check it out on PR #333 and contact me for some improvements! Can't wait on that.

**Comment by giorginogreg** [comment]
Please @markuspoerschke close this issue, thank you!
