### ISSUE TITLE
Eluceo\iCal\Domain\Entity\TimeZone::createFromPhpDateTimeZone can not work correctly

### ISSUE THREAD

**Issue by nbtai** [markuspoerschke/iCal#240]
in the example in [timeZone](https://ical.poerschke.nrw/components/timezone.html). 

```
use Eluceo\iCal\Domain\Entity\TimeZone;
use DateTimeZone as PhpDateTimeZone;

$timeZone = TimeZone::createFromPhpDateTimeZone(new PhpDateTimeZone('Europe/Berlin'));
```
I try to use but it throws the error.
```assert(): assert($fromDateTime instanceof DateTimeImmutable) failed```

It's seem that the 
```
 DateTimeImmutable::createFromFormat(
                DateTimeImmutable::ISO8601,
                $transitionArray['time']
            );
```
in [Domain/Entity/TimeZone.php#L47](https://github.com/markuspoerschke/iCal/blob/2.x/src/Domain/Entity/TimeZone.php#L47) receives the wrong format. So that It can not create the object.

**Comment by JorisDebonnet** [comment]
It indeed does not work if you only use one parameter. A workaround is to make sure you do specify the second and third parameter.

**Comment by markuspoerschke** [comment]
Mhmm, ok, it looks like that's not quite thought through.

I added `PHP_INT_MIN` and `PHP_INT_MAX` as default values for the lower and upper time stamp.

Unfortunately using `PHP_INT_MIN` results in the following date `-292277022657-01-27T08:29:52+0000`. This date cannot be parsed providing `\DateTimeInterface::ATOM` format, because it contains a year [B.C](https://en.wikipedia.org/wiki/Anno_Domini).

To me it looks like a rather bad idea to rely on the default values. I think the suggestion by @JorisDebonnet is not only a workaround, but the solution to the problem. The user of this library must use within which dates they operates.

To keep the current PHP API as it is, I will change the minimum default timestamp to the year of Christ birth (0000-01-01 12:00:00). According to Wikipedia, [the first daylight saving time was introduced on 30th of April 1916 ](https://en.wikipedia.org/wiki/Daylight_saving_time) in German Empire and Austria-Hungary. Therefore the first transition will be earliest April 30th 1916 anyhow.

**Comment by markuspoerschke** [comment]
@nbtai thanks for reporting the bug. I opened a pull request.

@JorisDebonnet thanks for the hint for the "workaround".
