### ISSUE TITLE
Bad ics file generation

### ISSUE THREAD

**Issue by Selion05** [markuspoerschke/iCal#241]
I just upgraded from  `2.x-dev 4eb1c90` to `2.x-dev cd1635a` and  
now i get a failing unit test
```
-TRIGGER:VALUE=DATE-TIME:20200601T080000Z
+TRIGGER;VALUE=DATE-TIME:20200601T080000Z
```
note the semi colon after `TRIGGER` instead of a colon.

Here is the  unit test for completeness

```php
        $event = new Event(new UniqueIdentifier('an-awesome-id'));
        $event
            ->touch(new Timestamp(new \DateTime('2020-06-01 08:00')))
            ->setSummary('Some Summary')
            ->setDescription('Some Description')
            ->setOccurrence(
                new TimeSpan(
                    new DateTime(new \DateTime('2020-06-01 12:00'), false),
                    new DateTime(new \DateTime('2020-06-01 13:00'), false),
                ),
            )
            ->setLocation(new Location('Some cool location'))
            ->addAlarm(
                new Alarm(
                    new Alarm\DisplayAction('Alarm reminder'),
                    new Alarm\AbsoluteDateTimeTrigger(new Timestamp(new \DateTime('2020-06-01 10:00'))),
                ),
            )
        ;

        $calendar = new Calendar([$event]);

        $componentFactory = new CalendarFactory();
        $calendarComponent = (string) $componentFactory->createCalendar($calendar);
```

**Comment by markuspoerschke** [comment]
@Selion05, thanks for your report.

In an early version, a colon instead of a semicolon was used by mistake.

This was fixed in https://github.com/markuspoerschke/iCal/pull/222.

Having a semicolon at that position is correct. The semicolon is separating the parameter name (`TRIGGER`) from the property (`VALUE`). The colon is separating it from the actual value (`20200601T080000Z`).

Do you have issues opening the resulting iCal file?

I could successfully open your example in Apple Calendars:

<img width="532" alt="image" src="https://user-images.githubusercontent.com/1222377/114593177-1664ee80-9c8c-11eb-9b3c-f91fc27c7935.png">

**Comment by markuspoerschke** [comment]
> I just upgraded from 2.x-dev 4eb1c90 to 2.x-dev cd1635a

I recommend upgrading to the stable tagged versions available.

**Comment by Selion05** [comment]
ah nice there is 2.0.0 now! upgraded :)


So a semi colon is used if that element has sub values (e.g. `VALUE`)? 
I'm asking because with a relative trigger `TRIGGER:-PT1H` it is still a colon.

Anyway just tested with google calendar and the semi colon is correct.

thanks for time!

**Comment by markuspoerschke** [comment]
> I'm asking because with a relative trigger TRIGGER:-PT1H it is still a colon.

That looks correct to me. `TRIGGER` is the Propertyname and `-PT1H` is the value.
