### ISSUE TITLE
Consider implementing X-MICROSOFT-CDO-BUSYSTATUS

### ISSUE THREAD

**Issue by barrymieny** [markuspoerschke/iCal#32]
We sometimes need to specify out-of-office (X-MICROSOFT-CDO-BUSYSTATUS:OOF) for the status, but this library doesn't support it at the moment. I don't know if this can be implemented as part of $event->setStatus or if it would need to be a separate new property. If this can't be implemented, is there a way to set a custom property manually?

**Comment by navarr** [comment]
Microsoft Extensions to iCal *might* be out of scope of this project.

Though it would be fairly easy to write your own MicrosoftEvent that extends Event.  You'd want to add a protected variable with getters and setters for your busystatus, and you'd want to overwrite buildPropertyBag().  In your new buildPropertyBag, you'd call parent::buildPropertyBag() and then do

`$this->properties->set('X-MICROSOFT-CDO-BUSYSTATUS', $busyStatus);` where $busyStatus is your busyStatus, of course.

**Comment by barrymieny** [comment]
Thanks, I'll have a look at that. I just thought it could possibly be included as another X-MICROSOFT-CDO-* property is already implemented for all-day events.

**Comment by navarr** [comment]
I did say *might*.  It's up to @markuspoerschke and I guess anyone who wants to write the code.

**Comment by markuspoerschke** [comment]
Hey, 
thanks for you ideas. At the moment we have already some Microsoft and Apple related features implemented. I think this quite useful because this is one of the major problem to keep the iCal file compatible with different readers. Common use cases are of course using Microsoft Outlook or Apple Calendar.

@barrymieny Feel free to open a merge request to add this functionality :smile: I the Microsft Busystatus related to the offical FBSTATUS? (https://tools.ietf.org/html/rfc5545#section-3.2.9)

**Comment by barrymieny** [comment]
@markuspoerschke, yes it does seem to be related. From what I can gather though, the Microsoft "OOF" value isn't equal to any of the RFC values. I will have a look at doing a merge after thinking through the best way to handle the "OOF" usage specifically. It would probably be best to just equate it to FBSTATUS BUSY.

**Comment by markuspoerschke** [comment]
I close this issue, because of #146 implements this feature.
