### ISSUE TITLE
Description doesn't allow new lines

### ISSUE THREAD

**Issue by DanFMoore** [markuspoerschke/iCal#62]
If I call `Event->setDescription()` with `"\n"` (so that the new line is rendered), then the description field ends up with a new line being inserted and appearing like this:

> DESCRIPTION:First line of description
> Second line of description

When this is imported into an application, then only the first line of the description appears.

If I call the same method with `'\n'` (a literal `\n`) then the description field ends up like this:

`DESCRIPTION:First line of description\\nSecond line of description`

When this is imported it results in a literal `\n` appearing.

What you want is this appearing in the file:

`DESCRIPTION:First line of description\nSecond line of description`

From digging around in the code it looks like you can swap this call in `Eluceo\iCal\Property\Event\Description`:

``` php
    public function getEscapedValue()
    {
        return PropertyValueUtil::escapeValueAllowNewLine((string) $this->value);
    }
```

with:

``` php
    public function getEscapedValue()
    {
        return PropertyValueUtil::escapeValue((string) $this->value);
    }
```

That appears to work, although I haven't tried running the tests

**Comment by navarr** [comment]
This is probably related to #61 and #53

**Comment by markuspoerschke** [comment]
Is this still relevant?

**Comment by nikosv** [comment]
Any solution or workaround on this?

**Comment by nikosv** [comment]
Sorry. it looks like the workaround is to use "dev-master" ;-)

**Comment by maskedjellybean** [comment]
This is an issue again. It seems like `\Eluceo\iCal\Component\Event::setDescription` needs a parameter we can use as a flag to say whether we want the value run through `\Eluceo\iCal\Property\StringValue::getEscapedValue`. At the moment there's no way to use line breaks in the description because they're escaped by this method.

EDIT: I realized I'm using an outdated version (0.17.0), so maybe this is resolved in version 2.x. I can't verify this because I'm using this library via another library and don't have control over the version that's used.
