### ISSUE TITLE
Add possibility to add custom calendar properties

### ISSUE THREAD

**Issue by bhofm** [markuspoerschke/iCal#82]
As far as I have seen in the code it is not possible to add custom properties, right?
Is there any reason for that? Maybe it was your intention to only support the properties defined by the RFC?

There are several already existing properties one might use (e.g. X-ALT-DESC, ...) or even custom properties only some clients may interpret (e.g. needed for a customer application).
Wouldn't it be helpful to add some kind of `setCustomProperties()/addCustomProperty()` functionality?

For now I have to extend your Component (e.g. Event) or manipulate the set of properties created by _buildPropertyBag()_?
It would be handy to be able to add such properties with your lib natively.

**Comment by bhofm** [comment]
Any opinions?

**Comment by markuspoerschke** [comment]
Hey @bhofm,

thanks for you question.

The original idea of this library was to create an abstraction layer for creating _.ics_ files. I wanted to avoid to think about any iCal related RFCs. Back then I was not thinking about the point that there are many more people using my library but needing more properties.

Depending on the feature it looks like a good idea to add the additional properties. This happend for example with the [geo location property for Apple](https://github.com/markuspoerschke/iCal/commit/25f65eb58f7949e69001591fe2b2edfe8b365614) or also regarding the X-ALT-DESC... you mentioned.

I think adding more properties is not a problem as long as they can be reused by other people. In this case feel free to add the missing properties to the application. If you need your very own properties, inheriting the `Event` class is a very good way to go. I would also prefer extending the components rather than adding a method that is directly coupled to the iCal standard to keep the abstraction for the developers.

Do you have an concreate example what kind of property you added?

**Comment by markuspoerschke** [comment]
For the upcoming version 2, it is possible to [add custom properties](https://ical.poerschke.nrw/advanced/custom-properties.html) to iCal components.

**Comment by bhofm** [comment]
Thanks!
