### ISSUE TITLE
Empty events after cancelling

### ISSUE THREAD

**Issue by naffiq** [markuspoerschke/iCal#84]
Hello and thank you for this great extension!

I'm having an issue with cancelling an event, which is creation of empty event.

For example I have downloaded an `.ics` file and added it to my calendar: http://bit.ly/2kZhUCf

Then I'm creating event cancellation file with this code:
```php
<?php
    /**
     * @param int $id
     * @return \Eluceo\iCal\Component\Event
     */
    public static function cancelICal(int $id): \Eluceo\iCal\Component\Event
    {
        return (new \Eluceo\iCal\Component\Event($id))
            ->setCancelled(true);
    }
```

And I get following result: http://bit.ly/2lCho0D

When I dig into generated `.ics` file, I see that it contains todays date:
```ics
BEGIN:VCALENDAR
VERSION:2.0
PRODID:mywebsite.com
X-PUBLISHED-TTL:P1W
BEGIN:VEVENT
UID:16927
DTSTART;VALUE=DATE:20170220
SEQUENCE:0
TRANSP:OPAQUE
CLASS:PUBLIC
STATUS:CANCELLED
X-MICROSOFT-CDO-ALLDAYEVENT:TRUE
DTSTAMP:20170220T163032Z
END:VEVENT
END:VCALENDAR
```
How can I override this behavior? Thanks in advance!

**Comment by navarr** [comment]
This is expected behavior.  iCal is a utility library, as such it does no storing of prior events for retrieval (as you seem to be expecting by creating an event with the ID).

You should utilize the same code that created the initial event and then add `->setCancelled(true)` to generate a new, stand-alone, cancelled event that maintains the same data as the original.

**Comment by markuspoerschke** [comment]
@naffiq does @navarr’s answer solve your problem?

**Comment by naffiq** [comment]
Thanks for the answer @navarr, I'll try it out!
@markuspoerschke yeah, I think that's it!
