### ISSUE TITLE
Adding 4 days in end date if no time is true

### ISSUE THREAD

**Issue by piyushkantm** [markuspoerschke/iCal#98]
There is an issue which is caused on the following conditions:

`$event = new Event('some UID')`
`$event->setDtStart($startDate);`
`$event->setDtEnd($endDate);`
`$event->setNoTime(true);`

What is the point of adding 1 day to the end date if no time is true?
https://github.com/markuspoerschke/iCal/blob/master/src/Component/Event.php#L261

This line gets executed 4 times and increases the end date by 4 days.

**Comment by navarr** [comment]
A workaround until a fix is implemented would be to create a new `$endDate` for each iteration.

The problem is, of course, that since the date is mutable when setNoTime increments the date it's incrementing the same object that's being passed around to all the events.

setNoTime indicates that it's an all day event, and so sets the endDate to exactly 24 hours after the start date.

The point of adding 1 day to the end date is documented by #83

**Comment by piyushkantm** [comment]
Thanks for quick response. but i do not follow what you mean by  

> create a new `$endDate` for each iteration

Even if we change `$this->dtEnd->add(new \DateInterval('P1D'));` to 
`$this->dtEnd = (clone $this->dtEnd)->add(new \DateInterval('P1D'));`

**Comment by markuspoerschke** [comment]
@piyushkantm Please check the test [here](https://github.com/markuspoerschke/iCal/commit/cecf7d0f173cdf10b5793aed9af8ef1d9034b8b0#diff-637c83f8ff90e4547f6a333fb669a1d8). Calling the `render` method from the component can cause two different results since the date is changed. From your pull request I can see that you fixed it there.

@piyushkantm I applied an updated version of #99 to master that also contains the fix from #100. Can you test that using `dev-master` of this package?

@piyushkantm Thanks for reporting the issue! :) Also I would like you for your Pull Request.
@navarr Thanks for your support as well! :)

**Comment by piyushkantm** [comment]
Yes, the dev-master works fine. Thanks

**Comment by markuspoerschke** [comment]
@piyushkantm cool, then I will create a new release so you can install a stable version.

**Comment by markuspoerschke** [comment]
Available in Version [0.12.1](https://github.com/markuspoerschke/iCal/releases/tag/0.12.1) now.

**Comment by piyushkantm** [comment]
thanks. I was already using the dev-master branch 😆
